const mongoose = require("mongoose");

const Item_masterSchema = mongoose.Schema({
    Type: { type: mongoose.Schema.Types.ObjectId, ref: 'Type' },
    refno: { type: String, default: "" },
    Color: { type: mongoose.Schema.Types.ObjectId, ref: 'Type' },
    Clarity: { type: mongoose.Schema.Types.ObjectId, ref: 'Type' },
    Shape: { type: mongoose.Schema.Types.ObjectId, ref: 'Type' },
    Size: { type: mongoose.Schema.Types.ObjectId, ref: 'Type' },
    lotno: { type: String, default: "" },
    kapan: { type: String, default: "" },
    asking_rate: { type: String, default: "" },
    cost: { type: String, default: "" },
    stock_value: { type: String, default: "" },
    Remarks: { type: String, default: "" },
    responsibility: { type: String, default: "" },
    pair: { type: String, default: "" },
    certificate_no: { type: String, default: "" },
    length: { type: String, default: "" },
    width: { type: String, default: "" },
    depth: { type: String, default: "" },
    depth_pct: { type: String, default: "" },
    table_pct: { type: String, default: "" },
    cut: { type: String, default: "" },
    polish: { type: String, default: "" },
    symmetry: { type: String, default: "" },
    fl_intensity: { type: String, default: "" },
    fl_color: { type: String, default: "" },
    inscription: { type: String, default: "" },
    girdle: { type: String, default: "" },
    girdle_condition: { type: String, default: "" },
    girdle_pct: { type: String, default: "" },
    culet_size: { type: String, default: "" },
    key_to_symbols: { type: String, default: "" },
    report_date: { type: String, default: "" },
    report_comments: { type: String, default: "" },
    crn_ag: { type: String, default: "" },
    crn_ht: { type: String, default: "" },
    pav_ag: { type: String, default: "" },
    pav_dp: { type: String, default: "" },
    str_ln: { type: String, default: "" },
    lr_half: { type: String, default: "" },
    current_date: { type: Date, default: "" },
    current_time: { type: Date, default: "" },
    user_id: { type: String, default: "" },
    Branch_id: { type: String, default: "" },
    master_country_id: { type: String, default: "" },
});

module.exports = mongoose.model("Item_master", Item_masterSchema);