const mongoose = require("mongoose");

const memoSchema = mongoose.Schema({
    date: { type: Date, required: true },
    inv_no: { type: Number, required: true },
    bill_no: { type: Number, required: true },
    party: { type: String, required: true },
    due_days: { type: String, required: true },
    due_date: { type: Date, required: true },
    over_due: { type: String, required: true },
    over_due_date: { type: Date, required: true },
    name: { type: String, required: true },
    remark: { type: String, required: true },
    total_carat: { type: Number, required: true },
    amount: { type: Number, required: true },
    currency: { type: String, required: true },
    curr_rate: { type: Number, required: true },
    final_amount_local: { type: Number, default: "" },
    paid_amount: { type: Number, default: "" },
    paid_amount_local: { type: Number, default: "" },
    remain_amount: { type: Number, default: "" },
    remain_amount_local: { type: Number, default: "" },
    cursor_amount: { type: Number, default: "" },
    broker: { type: String, required: true },
    p_r_type: { type: String, required: true },
    adat: { type: String, required: true },
    create_user_id: { type: String, default: "" },
    current_date: { type: Date, default: "" },
    current_time: { type: Date, default: "" },
    update_user_id: { type: String, default: "" },
    update_date: { type: Date, default: "" },
    update_time: { type: Date, default: "" },
    status: { type: Boolean, default: false },
    branch_id: { type: String, default: "" },
    master_country_id: { type: String, default: "" },
    trans_entries: [
        {
            refno: { type: String, ref: "Item_master", required: true },
            lotno: { type: String, required: true },
            total_carat: { type: Number, required: true },
            pcs: { type: Number, required: true },
            remain_carat: { type: Number, required: true },
            carat: { type: Number, required: true },
            rate: { type: Number, required: true },
            amount: { type: Number, required: true },
            remark: { type: String, required: true },
            cost: { type: String, default: "" },
            stock_value: { type: String, default: "" },
            status: { type: String, default: "" },
            create_user_id: { type: String, default: "" },
            current_date: { type: Date, default: "" },
            current_time: { type: Date, default: "" },
            update_user_id: { type: String, default: "" },
            update_date: { type: Date, default: "" },
            update_time: { type: Date, default: "" },
            branch_id: { type: String, default: "" },
            master_country_id: { type: String, default: "" },
        },
    ],
});

module.exports = mongoose.model("Memo_entry", memoSchema);
