const mongoose = require("mongoose");

const pur_saleSchema = mongoose.Schema({
  inv_type: { type: Boolean, default: false },
  date: { type: Date, required: true },
  type: { type: String, required: true },
  inv_no: { type: Number, required: true },
  bill_no: { type: Number, required: true },
  party: { type: String, required: true },
  due_days: { type: String, required: true },
  due_date: { type: Date, required: true },
  over_due: { type: String, required: true },
  over_due_date: { type: Date, required: true },
  name: { type: String, required: true },
  remark: { type: String, required: true },
  total_carat: { type: Number, required: true },
  amount: { type: Number, required: true },
  tax_per: { type: Number, required: true },
  tax_amount: { type: Number, required: true },
  curr_amount: { type: Number, required: true },
  final_amount: { type: Number, required: true },
  currency: { type: String, required: true },
  curr_rate: { type: Number, required: true },
  final_amount_local: { type: Number, default: ""  },
  paid_amount: { type: Number, default: "" },
  paid_amount_local: { type: Number, default: "" },
  remain_amount: { type: Number, default: "" },
  remain_amount_local: { type: Number, default: "" },
  cursor_amount: { type: Number, default: "" },
  broker: { type: String, required: true },
  broker_per: { type: Number, required: true },
  brok_amount: { type: Number, required: true },
  p_r_type: { type: String, required: true },
  adat: { type: String, required: true },
  adat_per: { type: Number, required: true },
  adat_amt: { type: Number, required: true },
  create_user_id: { type: String, default: "" },
  current_date: { type: Date, default: "" },
  current_time: { type: Date, default: "" },
  update_user_id: { type: String, default: "" },
  update_date: { type: Date, default: "" },
  update_time: { type: Date, default: "" },
  status: { type: Boolean, default: false },
  branch_id: { type: String, default: "" },
  master_country_id: { type: String, default: "" },
  trans_entries: [
    {
      refno: { type: String, ref: "Item_master", required: true },
      lotno: { type: String, required: true },
      pcs: { type: Number, required: true },
      carat: { type: Number, required: true },
      rate: { type: Number, required: true },
      amount: { type: Number, required: true },
      l1: { type: Number, required: true },
      l2: { type: Number, required: true },
      net_amount: { type: Number, required: true },
      kapan: { type: String, required: true },
      remark: { type: String, required: true },
      asking_rate: { type: Number, required: true },
      cost: { type: String, default: "" },
      stock_value: { type: String, default: "" },
      status: { type: String, default: "" },
      create_user_id: { type: String, default: "" },
      current_date: { type: Date, default: "" },
      current_time: { type: Date, default: "" },
      update_user_id: { type: String, default: "" },
      update_date: { type: Date, default: "" },
      update_time: { type: Date, default: "" },
      branch_id: { type: String, default: "" },
      master_country_id: { type: String, default: "" },
    },
  ],
});

module.exports = mongoose.model("Pur_sale", pur_saleSchema);
