const mongoose = require("mongoose");

const pur_saleSchema = mongoose.Schema({
    inv_type: { type: Boolean, default: false },
    date: { type: Date },
    type: { type: String },
    inv_no: { type: Number },
    bill_no: { type: Number },
    party: { type: String },
    due_days: { type: String },
    due_date: { type: Date },
    over_due: { type: String },
    over_due_date: { type: Date },
    name: { type: String },
    remark: { type: String },
    total_carat: { type: Number },
    amount: { type: Number },
    tax_per: { type: Number },
    tax_amount: { type: Number },
    curr_amount: { type: Number },
    final_amount: { type: Number },
    currency: { type: String },
    rate: { type: Number },
    final_amount_local: { type: Number },
    paid_amount: { type: Number },
    paid_amount_local: { type: Number },
    remain_amount: { type: Number },
    remain_amount_local: { type: Number },
    cursor_amount: { type: Number },
    broker: { type: String },
    broker_per: { type: Number },
    brok_amount: { type: Number },
    p_r_type: { type: String },
    adat: { type: String },
    adat_per: { type: Number },
    adat_amt: { type: Number },
    create_user_id: { type: String },
    current_date: { type: Date },
    current_time: { type: Date },
    update_user_id: { type: String },
    update_date: { type: Date },
    update_time: { type: Date },
    status: { type: Boolean, default: false },
    branch_id: { type: String },
    master_country_id: { type: String },
    trans_entries: [
        {
            refno: { type: String, ref: 'Item_master' },
            lotno: { type: String },
            pcs: { type: Number },
            carat: { type: Number },
            rate: { type: Number },
            amount: { type: Number },
            l1: { type: Number },
            l2: { type: Number },
            net_amount: { type: Number },
            kapan: { type: String },
            remark: { type: String },
            asking_rate: { type: Number },
            cost: { type: String },
            stock_value: { type: String },
            status: { type: String },
            create_user_id: { type: String },
            current_date: { type: Date },
            current_time: { type: Date },
            update_user_id: { type: String },
            update_date: { type: Date },
            update_time: { type: Date },
            branch_id: { type: String },
            master_country_id: { type: String },
        },
    ],
});

module.exports = mongoose.model("Pur_sale", pur_saleSchema);